ame: "Run Unit Tests"
description: "Execute Python Unit Tests"
inputs:
  directory:
    description: "Directory of lambda codebase"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9.16"
        cache: "pip"
        cache-dependency-path: "**/requirements_dev.txt"
    - name: Install Dependencies
      working-directory: lambdas/${{ inputs.directory }}
      run: pip install -r requirements_dev.txt
      shell: bash
    - name: Run Tests
      working-directory: lambdas/${{ inputs.directory }}
      run: python -m pytest tests/
      shell: bash
