name: "Configure AWS cli using OIDC Provider"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubDeployRole
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
