name: "Build Web Artifacts"
description: "Create build artifacts for react app in a given directory and upload during workflow"
inputs:
  directory:
    description: "Directory of React Project, will also be used to create artifact name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: "npm"
        cache-dependency-path: ${{ inputs.directory }}/package-lock.json
    # - name: Cache dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ${{ inputs.directory }}/node_modules
    #     key: ${{ format('{0}-{1}', runner.os, hashFiles(format('{0}/package-lock.json', inputs.directory)) ) }}
    #     # key: ${{ runner.os }}-${{ hashFiles('${{ inputs.directory }}/package-lock.json') }}
    - name: Build Deployment Artifact
      run: npm install && npm run build
      shell: bash
      working-directory: ${{ inputs.directory }}
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.directory }}-artifact
        path: ./${{ inputs.directory }}/dist/
        if-no-files-found: error
        retention-days: 1
