name: "Build Web Artifacts"
description: "Create build artifacts for react app in a given directory and upload during workflow"
inputs:
  directory:
    description: "Directory of React Project, will also be used to create artifact name"
    required: true
    default: ""
  artifact_bucket:
    description: "Bucket to save production build in, used as a cache, build will be pulled from here if no changes to code directory"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: "npm"
        cache-dependency-path: ${{ inputs.directory }}/package-lock.json
    - name: Install Dependencies
      working-directory: ${{ inputs.directory }}
      run: npm ci
      shell: bash
    - name: Build Deployment Artifact
      working-directory: ${{ inputs.directory }}
      run: npm run build
      shell: bash
    - name: Archive Build Artifact
      working-directory: ${{ inputs.directory }}
      run: aws s3 sync dist/ s3://${{ inputs.artifact_bucket}}/${{ inputs.directory }} -- delete
      shell: bash
