name: "Build Web Artifacts"
description: "Create build artifacts for react app in a given directory and upload during workflow"
inputs:
  directory:
    description: "Directory of React Project, will also be used to create artifact name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: "npm"
        cache-dependency-path: ${{ inputs.directory }}/package-lock.json
    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.directory }}/node_modules
        key: ${{ format('{0}-{1}', runner.os, hashFiles(format('{0}/package-lock.json', inputs.directory)) ) }}
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.directory }}
      run: npm install
      shell: bash
    - name: Build Deployment Artifact
      working-directory: ${{ inputs.directory }}
      run: npm run build
      shell: bash
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.directory }}-artifact
        path: ./${{ inputs.directory }}/dist/
        if-no-files-found: error
        retention-days: 1
