name: "Build Web Artifacts"
description: "Create build artifacts for react app"
inputs:
  directory:
    description: "Directory of React Project"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: "npm"
        cache-dependency-path: ${{ inputs.directory }}/package-lock.json
    - name: Install Dependencies
      working-directory: ${{ inputs.directory }}
      run: npm ci
      shell: bash
    - name: Build Deployment Artifact
      working-directory: ${{ inputs.directory }}
      run: npm run build
      shell: bash
