interface IEnvironment {
  VITE_USERPOOL_ID: string;
  VITE_USERPOOL_WEB_CLIENT_ID: string;
  VITE_AWS_REGION: string;
  VITE_COGNITO_DOMAIN: string;
  VITE_BASE_API_URL: string;
  VITE_MAPBOX_ACCESS_TOKEN: string;
  VITE_MAPBOX_URL: string;
  VITE_ASSETS_BASE_URL: string;
  VITE_APPSYNC_API_URL: string;
  VITE_APPSYNC_AUTH_TYPE: string;
  VITE_APPSYNC_API_KEY: string;
  MAPBOX_STYLE: string;
}

export const ENV: IEnvironment = {
  VITE_USERPOOL_ID: import.meta.env.VITE_USERPOOL_ID,
  VITE_USERPOOL_WEB_CLIENT_ID: import.meta.env.VITE_USERPOOL_WEB_CLIENT_ID,
  VITE_AWS_REGION: import.meta.env.VITE_AWS_REGION,
  VITE_COGNITO_DOMAIN: import.meta.env.VITE_COGNITO_DOMAIN,
  VITE_BASE_API_URL: import.meta.env.VITE_BASE_API_URL,
  VITE_MAPBOX_ACCESS_TOKEN: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
  VITE_MAPBOX_URL: import.meta.env.VITE_MAPBOX_URL,
  VITE_ASSETS_BASE_URL: import.meta.env.VITE_ASSETS_BASE_URL,
  VITE_APPSYNC_API_URL: import.meta.env.VITE_APPSYNC_API_URL,
  VITE_APPSYNC_AUTH_TYPE: import.meta.env.VITE_APPSYNC_AUTH_TYPE,
  VITE_APPSYNC_API_KEY: import.meta.env.VITE_APPSYNC_API_KEY,
  MAPBOX_STYLE: "mapbox://styles/mapbox/streets-v12",
};
