export enum STYLING_CONFIG {
  MOBILE_ICON_BOX_SIZE = "38",
  MOBILE_ICON_VARIANT = "ghost",
  MOBILE_ICON_COLOR = "white",
  MOBILE_DRAWER_TOP_BUTTON_OFFSET = "15",
  MOBILE_DRAWER_BOTTOM_BUTTON_OFFSET = "5",
  MOBILE_DRAWER_LEFT_RIGHT_BUTTON_OFFSET = "5",
  WEB_MODAL_TOP_BUTTON_OFFSET = "5",
}
