export enum STYLING_CONFIG {
  MOBILE_ICON_BOX_SIZE = "38",
  COLOR_PRIMARY = "primary",
  COLOR_SECONDARY = "secondary",
  WEB_ICON_BOX_SIZE = "50",
  MOBILE_SEARCH_BAR_CHIP_SIZE = "small",
  WEB_SEARCH_BAR_CHIP_SIZE = "medium",
  MOBILE_SEARCH_BAR_FONT_SIZE = 15,
  WEB_SEARCH_BAR_FONT_SIZE = 25,
  MOBILE_SEARCH_BAR_MAX_HEIGHT = "20rem",
  WEB_SEARCH_BAR_MAX_HEIGHT = "40rem",
  MOBILE_USER_MENU_FONT_SIZE = "body2",
  WEB_USER_MENU_FONT_SIZE = "h4",
}
