name: Main Application

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET_MANAGER_NAME: ${{ secrets.GOOGLE_CLIENT_SECRET_MANAGER_NAME }}
  IMAGE_PROCESSOR_SECRET_NAME: ${{ secrets.IMAGE_PROCESSOR_SECRET_NAME }}
  IMAGE_PROCESSOR_SECRET_KEY: ${{ secrets.IMAGE_PROCESSOR_SECRET_KEY }}
  ARTIFACT_BUCKET: ${{ vars.ARTIFACT_BUCKET }}
on:
  push:
    branches:
      - main
      - feature*
    paths:
      - "cdk-stacks/**"
      - ".github/**"
      - "admin-portal/**"
      - "client-web/**"
      - "lambdas/**"
jobs:
  change-detector:
    name: Detect File Changes And Artifact Existence
    runs-on: ubuntu-latest
    outputs:
      pipeline: ${{ steps.filter.outputs.pipeline }}
      web-client: ${{ steps.filter.outputs.web-client }}
      admin-portal: ${{ steps.filter.outputs.admin-portal }}
      image-processor: ${{ steps.filter.outputs.image-processor }}
      app-server: ${{ steps.filter.outputs.app-server }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            pipeline:
              - '.github/**'
            web-client:
              - 'client-web/**'
            admin-portal:
              - 'admin-portal/**'
            image-processor:
              - 'lambdas/image_processor/**'
            app-server:
              - 'lambdas/app_server/**'
  build-admin-portal:
    needs: change-detector
    if: ${{ needs.change-detector.outputs.admin-portal == 'true' || needs.change-detector.outputs.pipeline == 'true'}}
    name: Create Admin Portal Artifact
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS CLI and Credentials
        uses: ./.github/actions/configure-aws-cli
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-web-artifact
        with:
          directory: "admin-portal"
          artifact_bucket: $ARTIFACT_BUCKET
  build-client-web:
    needs: change-detector
    if: ${{ needs.change-detector.outputs.web-client == 'true' || needs.change-detector.outputs.pipeline == 'true'}}
    name: Create Web Client Artifact
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS CLI and Credentials
        uses: ./.github/actions/configure-aws-cli
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-web-artifact
        with:
          directory: "client-web"
          artifact_bucket: $ARTIFACT_BUCKET
  test-image-processor-lambda:
    needs: change-detector
    if: ${{ needs.change-detector.outputs.image-processor == 'true' || needs.change-detector.outputs.pipeline == 'true'}}
    name: Run Image Processor Unit Tests
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS CLI and Credentials
        uses: ./.github/actions/configure-aws-cli
      - name: Run Unit Tests
        uses: ./.github/actions/run-python-lambda-tests
        with:
          directory: "image_processor"
  test-app-server-lambda:
    needs: change-detector
    if: ${{ needs.change-detector.outputs.app-server == 'true' || needs.change-detector.outputs.pipeline == 'true'}}
    name: Run App Server Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        uses: ./.github/actions/run-python-lambda-tests
        with:
          directory: "app_server"
  deploy:
    name: Build/Deploy Application Infrastructure
    runs-on: ubuntu-latest
    needs:
      [
        build-admin-portal,
        build-client-web,
        test-image-processor-lambda,
        test-app-server-lambda,
      ]
    if: |
      always() && 
      !contains(needs.*.result, 'failure') && 
      !contains(needs.*.result, 'cancelled')
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS CLI and Credentials
        uses: ./.github/actions/configure-aws-cli
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: "npm"
          cache-dependency-path: cdk-stacks/app/package-lock.json
      - name: Download Admin Portal Artifact
        working-directory: admin-portal
        run: aws s3 sync s3://$ARTIFACT_BUCKET/admin-portal/ dist/ && cd dist && ls
      - name: Download Web Client Artifact
        working-directory: client-web
        run: aws s3 sync s3://$ARTIFACT_BUCKET/client-web/ dist/ && cd dist && ls
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install Dependencies
        working-directory: cdk-stacks/app
        run: npm ci
      - name: Test Synth Step
        if: github.ref != 'refs/heads/main'
        working-directory: cdk-stacks/app
        run: cdk synth
      - name: Deploy Stack
        if: github.ref == 'refs/heads/main'
        working-directory: cdk-stacks/app
        run: cdk deploy --require-approval "never"
