name: Main Application

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
  push:
    branches:
      - main
    paths:
      - "cdk-stacks/app/**"
      - ".github/workflows/app.yaml"
      - ".github/actions/**"
      - "admin-portal/**"
      - "client-web/**"
jobs:
  build-admin-portal:
    name: Create Admin Portal Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-web-artifact
        with:
          directory: "admin-portal"
  build-client-web:
    name: Create Web Client Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-web-artifact
        with:
          directory: "client-web"
  deploy:
    name: Build/Deploy Application Infrastructure
    runs-on: ubuntu-latest
    needs: [build-admin-portal, build-client-web]
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS CLI and Credentials
        uses: ./.github/actions/configure-aws-cli
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: Download Admin Portal Artifact
        uses: actions/download-artifact@v3
        with:
          name: admin-portal-artifact
          path: ./admin-portal/dist/
      - name: Download Web Client Artifact
        uses: actions/download-artifact@v3
        with:
          name: client-web-artifact
          path: ./client-web/dist/
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install Dependencies
        run: cd cdk-stacks/app && npm install
      - name: Synth Stack
        run: cd cdk-stacks/app && cdk synth
      - name: Deploy Stack
        run: cd cdk-stacks/app && cdk deploy --require-approval "never"
