name: oidc-test
on:
  push:
    branches:
      - main
    paths:
      - "cdk-stacks/github-actions-stack/**"
jobs:
  deploy:
    name: Test OIDC Permissions
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCESS_KEY_ID }}:role/GitHubDeployRole
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Test AWS Permissions
        run: aws s3 ls
